appsanator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views
from .views import register_view
from .views import review_view
from .views import login_view
from .views import my_logout_view
from .views import расписаниедневное
from .views import feedbacks
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include

urlpatterns = [
    path('', views.base, name='home'),
    path('ban', views.ban, name='ban'),
    path('rules', views.rules, name='rules'),
    path('daily', views.daily, name='daily'),
    path('posters', views.posters, name='posters'),
    path('link', views.link, name='link'),
    path('map', views.map, name='map'),
    path('services', views.services, name='services'),
    path('daily/', расписаниедневное, name='daily-view'),
    path('schedule/<int:user_id>/<str:day>/', views.расписаниепользователя, name='schedule-for-user'),
    path('login/', login_view, name='login'),
    path('logout/', my_logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('review/', views.review_view, name='review'),
    path('feedbacks/', feedbacks, name='feedbacks'),
    path('sw.js', views.ServiceWorkerView.as_view(), name=views.ServiceWorkerView.name,),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.conf import settings
from django import forms


# class UserDailySchedule(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     weekday = models.CharField(max_length=10)
#     schedule = models.TextField()
#
#     def __str__(self):
#         return f'{self.weekday} - {self.user.username}'

# class UserDailySchedule(models.Model):
#     WEEKDAY_CHOICES = (
#         ('Понедельник', 'Понедельник'),
#         ('Вторник', 'Вторник'),
#         ('Среда', 'Среда'),
#         ('Четверг', 'Четверг'),
#         ('Пятница', 'Пятница'),
#         ('Суббота', 'Суббота'),
#         ('Воскресенье', 'Воскресенье'),
#     )
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     schedule = models.CharField(max_length=200,  null=True)
#     weekday = models.CharField(max_length=11, choices=WEEKDAY_CHOICES)
#     start_time = models.DateTimeField(default=datetime.datetime(2023, 6, 21, 0, 0))
#     end_time = models.TimeField(default=datetime.time(0, 0), blank=True, null=True)
#     description = models.TextField( null=True)
#
#     def str(self):
#         return self.schedule

# class UserDailySchedule(models.Model):
#     WEEKDAY_CHOICES = (
#         ('понедельник', 'Понедельник'),
#         ('вторник', 'Вторник'),
#         ('среда', 'Среда'),
#         ('четверг', 'Четверг'),
#         ('пятница', 'Пятница'),
#         ('суббота', 'Суббота'),
#         ('воскресенье', 'Воскресенье'),
#     )
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     schedule = models.CharField(max_length=200, blank=True, null=True)
#     weekday = models.CharField(max_length=11, choices=WEEKDAY_CHOICES)
#     start_time = models.DateTimeField(default=datetime.datetime(2023, 6, 21, 0, 0))
#     end_time = models.TimeField(default=datetime.time(0, 0))
#     description = models.TextField(blank=True, null=True)
#
#     def str(self):
#         return self.schedule


class Rools(models.Model):
    title = models.CharField('Название', max_length=300)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Правило'
        verbose_name_plural = 'Правила'


class Rasporiadok(models.Model):
    title = models.CharField('Название', max_length=300)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Распорядок дня'
        verbose_name_plural = 'Распорядок дней'


class Posters(models.Model):
    title = models.CharField('Название', max_length=50)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='posters/', default='default.png')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Афиша'
        verbose_name_plural = 'Афиши'


class Zapret(models.Model):
    title = models.CharField('Название', max_length=300)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Запрет'
        verbose_name_plural = 'Запреты'


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    goal_choice = models.CharField(max_length=50, choices=(
        ('', ''),
        ('лечение', 'Лечение'),
        ('оздоровление', 'Оздоровление'),
        ('отдых', 'Отдых'),
    ), default='', verbose_name="Цель выбора здравницы", null=True, blank=True)
    visit_choice = models.CharField(max_length=50, choices=(
        ('', ''),
        ('впервые', 'Впервые'),
        ('повторно', 'Повторно'),
        ('более двух раз', 'Более двух раз'),
    ), default='', verbose_name="Посещаете данную здравницу", null=True, blank=True)
    istochnik = models.CharField(max_length=100, verbose_name="Источник", null=True, blank=True)
    # istochnik = models.CharField(max_length=50, choices=(
    #     ('', ''),
    #     ('знакомые', 'Знакомые'),
    #     ('реклама', 'Реклама'),
    #     ('другой вариант', 'Другой вариант'),
    # ), default='', verbose_name="Источник получения информации")
    kak_preobletali = models.CharField(max_length=50, choices=(
        ('', ''),
        ('полная стоимость', 'Полная стоимость'),
        ('льготная стоимость', 'Льготная стоимость'),
    ), default='', verbose_name="Как приобретали путевку", null=True, blank=True)
    gruppa = models.CharField(max_length=50, choices=(
        ('', ''),
        ('не имею', 'не имею'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
    ), default='', verbose_name="Группа ограничений трудоспособности", null=True, blank=True)
    treatment_rating = models.CharField(max_length=50, choices=(
        ('', ''),
        ('1', '1 - Плохо'),
        ('2', '2 - Удовлетворительно'),
        ('3', '3 - Хорошо'),
        ('4', '4 - Очень хорошо'),
        ('5', '5 - Отлично'),
    ), default='', verbose_name="Оценка качества лечения", null=True, blank=True)
    service_rating = models.CharField(max_length=50, choices=(
        ('', ''),
        ('1', '1 - Плохо'),
        ('2', '2 - Удовлетворительно'),
        ('3', '3 - Хорошо'),
        ('4', '4 - Очень хорошо'),
        ('5', '5 - Отлично'),
    ), default='', verbose_name="Оценка качества сервиса", null=True, blank=True)
    projivanie = models.CharField(max_length=50, choices=(
        ('', ''),
        ('1', '1 - Плохо'),
        ('2', '2 - Удовлетворительно'),
        ('3', '3 - Хорошо'),
        ('4', '4 - Очень хорошо'),
        ('5', '5 - Отлично'),
    ), default='', verbose_name="Оценка качества проживания", null=True, blank=True)
    pitanie = models.CharField(max_length=50, choices=(
        ('', ''),
        ('1', '1 - Плохо'),
        ('2', '2 - Удовлетворительно'),
        ('3', '3 - Хорошо'),
        ('4', '4 - Очень хорошо'),
        ('5', '5 - Отлично'),
    ), default='', verbose_name="Оценка качества питания", null=True, blank=True)
    soc_deatel = models.CharField(max_length=50, choices=(
        ('', ''),
        ('1', '1 - Плохо'),
        ('2', '2 - Удовлетворительно'),
        ('3', '3 - Хорошо'),
        ('4', '4 - Очень хорошо'),
        ('5', '5 - Отлично'),
    ), default='', verbose_name="Оценка качества социокультурной деятельности", null=True, blank=True)
    kval_med_pers = models.CharField(max_length=50, choices=(
        ('', ''),
        ('1', '1 - Плохо'),
        ('2', '2 - Удовлетворительно'),
        ('3', '3 - Хорошо'),
        ('4', '4 - Очень хорошо'),
        ('5', '5 - Отлично'),
    ), default='', verbose_name="Оценка качества квалификации медицинского персонала", null=True, blank=True)
    vrach = models.CharField(max_length=50, choices=(
        ('', ''),
        ('1', '1 - Плохо'),
        ('2', '2 - Удовлетворительно'),
        ('3', '3 - Хорошо'),
        ('4', '4 - Очень хорошо'),
        ('5', '5 - Отлично'),
    ), default='', verbose_name="Оценка культуры обслуживания врачей", null=True, blank=True)
    sred_med = models.CharField(max_length=50, choices=(
        ('', ''),
        ('1', '1 - Плохо'),
        ('2', '2 - Удовлетворительно'),
        ('3', '3 - Хорошо'),
        ('4', '4 - Очень хорошо'),
        ('5', '5 - Отлично'),
    ), default='', verbose_name="Оценка культуры обслуживания среднего медицинского персонала", null=True, blank=True)
    obsluj = models.CharField(max_length=50, choices=(
        ('', ''),
        ('1', '1 - Плохо'),
        ('2', '2 - Удовлетворительно'),
        ('3', '3 - Хорошо'),
        ('4', '4 - Очень хорошо'),
        ('5', '5 - Отлично'),
    ), default='', verbose_name="Оценка культуры обсуживающего персонала", null=True, blank=True)
    kak_v_celom = models.CharField(max_length=50, choices=(
        ('', ''),
        ('удовлетворительно', 'Удовлетворительно'),
        ('хорошо', 'Хорошо'),
        ('отлично', 'Отлично'),
    ), default='', verbose_name="Как в целом Вы можете оценить впечатления от пребывания в санатории", null=True,
                                   blank=True)
    kakova_ver = models.CharField(max_length=50, choices=(
        ('', ''),
        ('0', 'ни в коем случае'),
        ('1', 'Вряд ли'),
        ('2', 'Возможно'),
        ('3', 'Скорее всего да'),
        ('4', 'Расскажу конечно'),
        ('5', 'обязательно порекомендую'),
    ), default='', verbose_name="Какова вероятность что вы порекомендуете данную здравницу друзьям", null=True,
                                  blank=True)
    # opros = models.CharField(max_length=50, choices=(
    #     ('', ''),
    #     ('0', 'ни в коем случае'),
    #     ('1', 'Вряд ли'),
    #     ('2', 'Возможно'),
    #     ('3', 'Скорее всего да'),
    #     ('4', 'Расскажу конечно'),
    #     ('5', 'обязательно порекомендую'),
    # ), default='', verbose_name="Какова вероятность что вы порекомендуете данную здравницу друзьям", null=True, blank=True)
    age = models.PositiveIntegerField(verbose_name="Возраст", default=0, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=(('м', 'М'), ('ж', 'Ж'), ('', '')), verbose_name="Пол", default='',
                              null=True, blank=True)
    city = models.CharField(max_length=100, verbose_name="Город", default='', null=True, blank=True)
    rating = models.CharField(max_length=6, choices=(
    ('', ''), ('★☆☆☆☆', '1★'), ('★★☆☆☆', '2★'), ('★★★☆☆', '3★'), ('★★★★☆', '4★'), ('★★★★★', '5★')),
                              verbose_name="Оценка", default='', null=True, blank=True)
    text = models.TextField(verbose_name="отзыв", null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, verbose_name="дата")

    # istochnik = models.CharField(max_length=50, choices=(
    #     ('', ''),
    #     ('знакомые', 'Знакомые'),
    #     ('реклама', 'Реклама'),
    #     ('другой вариант', 'Другой вариант'),
    # ), default='')
    def __str__(self):
        return f"Отзыв от {self.user.username} {self.user.last_name}"

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

main/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Review
from .models import UserProfile
from django.contrib.auth import get_user_model
from main.models import UserProfile
from django.forms import ModelForm
from .models import Posters
from .models import Feedback
from django.core.exceptions import ValidationError


class ImageForm(ModelForm):
    class Meta:
        model = Posters
        fields = ['title', 'description', 'image']

class CustomUserCreationForm(UserCreationForm):
    last_name = forms.CharField(max_length=30, required=True, label='Фамилия')
    phone_number = forms.CharField(max_length=30, required=True, label='Номер телефона')
    password1 = forms.CharField(max_length=30, widget=forms.PasswordInput, label='Пароль')
    password2 = forms.CharField(max_length=30, widget=forms.PasswordInput, label='Повторите пароль')

    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.last_name = self.cleaned_data['last_name']
        phone_number = self.cleaned_data['phone_number']
        user.set_password(self.cleaned_data['password1'])
        user.save()

        if commit:
            # Create UserProfile
            UserProfile.objects.create(
                user=user,
                phone_number=phone_number
            )

        return user
    class Meta:
        model = User
        fields = ('username', 'last_name', 'phone_number', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
        }



class ReviewForm(forms.ModelForm):
    istochnik = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control ml-0'}),
        label='Назовите источник получения информации о данной здравнице',
        required=False # Make this field optional
    )
    age = forms.IntegerField(label="Возраст", required=False)
    gender = forms.ChoiceField(
        choices=(('м', 'М'), ('ж', 'Ж'), ('', '')),
        # widget=forms.RadioSelect,
        label="Пол",
        required = False

    )
    city = forms.CharField(label="Город", required=False)
    rating = forms.ChoiceField(
        choices=(('', ''), ('★☆☆☆☆', '1★'), ('★★☆☆☆', '2★'),('★★★☆☆', '3★'), ('★★★★☆', '4★'), ('★★★★★', '5★')),
        # widget=forms.RadioSelect,
        label="Оценка",
        required=False

    )
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 5, 'class': 'form-control'}),label='Ваши пожелания', required=False)

    class Meta:
        model = Review
        fields = ['goal_choice',
                  'visit_choice',
                  'istochnik',
                  'kak_preobletali',
                  'gruppa',
                  'treatment_rating',
                  'service_rating',
                  'projivanie',
                  'pitanie',
                  'soc_deatel',
                  'kval_med_pers',
                  'vrach',
                  'sred_med',
                  'obsluj',
                  'kak_v_celom',
                  'kakova_ver',
                  'age',
                  'gender',
                  'city',
                  'rating',
                  'text',]
        labels = {
            'goal_choice': 'Цель выбора здравницы',
            'visit_choice': 'Посещаете данную здравницу',
            'istochnik': 'Назовите источник получения информации о данной здравнице',
            'kak_preobletali': 'Как приоблетали путевку',
            'gruppa': 'Имеете ли Вы установленную группу ограничения трудоспособности',
            'treatment_rating': 'Оцените качество лечения',
            'service_rating': 'Оцените качество сервисых услуг',
            'projivanie': 'Оцените качество проживание',
            'pitanie': 'Оцените качество питание',
            'soc_deatel': 'Оцените качество социокультурной деятельности',
            'kval_med_pers': 'Оцените качество квалификации медицинского персонала',
            'vrach': 'Оценка культуры обслуживания врачей',
            'sred_med': 'Оценка культуры обслуживания среднего медицинского персонала',
            'obsluj': 'Оценка культуры обсуживающего персонала',
            'kak_v_celom': 'Как в целом Вы можете оценить впечатления от пребывания в санатории',
            'kakova_ver': 'Какова вероятность что вы порекомендуете данную здравницу друзьям',
            'age': 'Возраст',
            'gender': 'Пол',
            'city': 'Город',
            'rating': 'Оценка',
            'text': '',
        }

    def save(self, commit=True, user=None):
        review = super().save(commit=False)
        review.user = user
        if commit:
            review.save()
        return review


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['goal_choice', 'comment']

main/templates/main/ban.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Запрещается</title>
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500&family=Lobster&display=swap" rel="stylesheet">
</head>
<body>

<div class="mainGradient">

    <header>
        Запрещается
    </header>
    
    <div class="rules">
        {% for el in zapret %}
        <div>{{ el.title }}</div>
    {% endfor %}
    </div>


    <div class="buttonsBack">
        <a class="buttonBack" href="{% url 'home' %}">Главная</a>
    </div>
</div>
<script>
       if ('serviceWorker' in navigator) {
           navigator.serviceWorker.register('{% url "sw.js" %}', { scope: '/' }).then(function(reg) {
               // registration worked
               console.log('Registration succeeded. Scope is ' + reg.scope);
           }).catch(function(error) {
               // registration failed
               console.log('Registration failed with ' + error);
           });
       }

</script>
</body>
</html>

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Главная</title>
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <link rel="stylesheet" href="{% static 'main/css/Main-page.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500&family=Lobster&display=swap" rel="stylesheet">
</head>
<body>
      {% block content %}
      {% endblock %}
<div class="mainDiv">
  <div class="campTitle">Название санатория</div>
  <div class="welcomeText">Добро пожаловать</div>

  {% if user.is_authenticated %}
    <div class="loginus">
      <a class="btn" href="#"> </a>
    </div>
  {% else %}
    <div class="login">
      <a class="btn" href="{% url 'register' %}">Регистрация</a>
    </div>
  {% endif %}

  <div class="allLinks">
    <div class="link"><a href="{% url 'rules' %}">Правила для отдыхающих</a></div>

    {% if user.is_authenticated %}
      <div class="link"><a href="{% url 'daily-view' %}">Санаторно-курортная книжка</a></div>
    {% endif %}

    <div class="link"><a href="{% url 'services' %}">Услуги</a></div>
    <div class="link"><a href="{% url 'map' %}">Схема</a></div>
    <div class="link"><a href="{% url 'posters' %}">Афиша</a></div>
    <div class="link"><a href="{% url 'link' %}">Связь</a></div>

    {% if not user.is_authenticated %}
      <div class="link"><a href="{% url 'review' %}">Отзывы</a></div>
    {% endif %}
  </div>

  {% if user.is_authenticated %}
    <div class="linkus center"><a href="{% url 'review' %}">Отзывы</a></div>
  {% endif %}
</div>



<script>
       if ('serviceWorker' in navigator) {
           navigator.serviceWorker.register('{% url "sw.js" %}', { scope: '/' }).then(function(reg) {
               // registration worked
               console.log('Registration succeeded. Scope is ' + reg.scope);
           }).catch(function(error) {
               // registration failed
               console.log('Registration failed with ' + error);
           });
       }

</script>
</body>
</html>

main/templates/main/daily.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Расписание дня</title>
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500&family=Lobster&display=swap" rel="stylesheet">
</head>
<body>



<div class="mainGradient">

    <header>
        Расписание дня
    </header>
    <div class="rules">
     {% for el in rasporiadok %}
        <div class="oneRules">{{ el.title }}</div>
    {% endfor %}
    </div>


    <div class="buttonsBack">
        <a class="buttonBack" href="{% url 'home' %}">Главная</a>
    </div>
</div>
<script>
       if ('serviceWorker' in navigator) {
           navigator.serviceWorker.register('{% url "sw.js" %}', { scope: '/' }).then(function(reg) {
               // registration worked
               console.log('Registration succeeded. Scope is ' + reg.scope);
           }).catch(function(error) {
               // registration failed
               console.log('Registration failed with ' + error);
           });
       }

</script>
</body>
</html>

main/templates/main/feedbacks.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}

    <div class="form-group">
        <label for="id_goal_choice">Цель выбора здравницы:</label>
        {{ form.goal_choice }}
    </div>

<!--    <div class="form-group">-->
<!--        <label for="id_comment">Комментарий:</label>-->
<!--        {{ form.comment }}-->
<!--    </div>-->

    <button type="submit">Отправить</button>
</form>
</body>
</html>

main/templates/main/link.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Связь</title>
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500&family=Lobster&display=swap" rel="stylesheet">
</head>
<body>

<header>Связь</header>

<div class="mainGradientt" style="font-family: 'IBM Plex Sans'; padding: 10px 20px; font-size: 25px;">


            <div class='quest'>Возник вопрос? Звоните нам!</div>
            {% for link in links %}
            <div style="font-weight: 600; margin-top: 6%;">{{ link.title|default:"" }}</div>
            <div style="text-align: left; font-size: 23px; margin-top: 3%; margin-bottom: 3%;">{{ link.content|default:"" }}</div>
            <a style="color: #3F92D2; font-size: 23px;" href=`tel:{{ link.tel1|default:"" }}`>{{ link.tel1|default:"" }}</a>
            <a style="color: #3F92D2; font-size: 23px;" href=`tel:{{ link.tel2|default:"" }}`>{{ link.tel2|default:"" }}</a>
            <a style="color: #3F92D2; font-size: 23px;" href=`tel:{{ link.tel3|default:"" }}`>{{ link.tel3|default:"" }}</a>
            {% endfor %}

            <img src="../../../static/main/assets/фонсвязи.png" />

    <div class="buttonsBack" style="margin-top: -5%;">
        <a class="buttonBack" href="{% url 'home' %}">Главная</a>
    </div>
</div>

<script>
       if ('serviceWorker' in navigator) {
           navigator.serviceWorker.register('{% url "sw.js" %}', { scope: '/' }).then(function(reg) {
               // registration worked
               console.log('Registration succeeded. Scope is ' + reg.scope);
           }).catch(function(error) {
               // registration failed
               console.log('Registration failed with ' + error);
           });
       }

</script>
</body>
</html>

main/templates/main/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Главная</title>
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500&family=Lobster&display=swap" rel="stylesheet">
</head>
<body>

{% block content %}
    <form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button" type="submit">Log in</button>
</form>
{% endblock %}
<div class="buttonsBack" style="margin-top: 60px;">
    <a class="buttonBack" href="{% url 'home' %}">Главная</a>
</div>
<script>
       if ('serviceWorker' in navigator) {
           navigator.serviceWorker.register('{% url "sw.js" %}', { scope: '/' }).then(function(reg) {
               // registration worked
               console.log('Registration succeeded. Scope is ' + reg.scope);
           }).catch(function(error) {
               // registration failed
               console.log('Registration failed with ' + error);
           });
       }

</script>
</body>
</html>

main/templates/main/posters.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Афиша</title>
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500&family=Lobster&display=swap" rel="stylesheet">
</head>
<body>



<div class="mainGradient">

    <header>Афиша</header>

    <div class="events">

        
       {% for poster in posters %}
    <div class="dayWeek">{{ poster.title }}</div>
    <div class="eventWeek">
        <text style="margin-left: auto;margin-right: auto;">{{ poster.description }}</text>
        <img src="{{ poster.image.url }}" alt="{{ poster.title }}">
    </div>
{% endfor %}
        


    <div class="buttonsBack">
        <a class="buttonBack" href="{% url 'home' %}">Главная</a>
    </div>
</div>
<script>
       if ('serviceWorker' in navigator) {
           navigator.serviceWorker.register('{% url "sw.js" %}', { scope: '/' }).then(function(reg) {
               // registration worked
               console.log('Registration succeeded. Scope is ' + reg.scope);
           }).catch(function(error) {
               // registration failed
               console.log('Registration failed with ' + error);
           });
       }

</script>
</body>
</html>